Update go.mod deps, bump to Go 1.19 (#274)
* Update go.mod deps, explicitly keep golang.org/x/sys at Go 1.16

* Let's drop support for Go 1.16, since golang.org/x/crypto fails to build too

Error: ../../../go/pkg/mod/golang.org/x/crypto@v0.22.0/ssh/cipher.go:19:2: //go:build comment without // +build comment
Error: ../../../go/pkg/mod/golang.org/x/crypto@v0.22.0/ssh/kex.go:19:2: //go:build comment without // +build comment

* Bump to Go 1.18 as minimal supported version

* Update examples to github.com/go-chi/chi@v5

* go mod tidy; update _example deps

* Use git describe --tags

* Bump to Go 1.19 to support golang.org/x/tools 2022+